image:
  name: gcr.io/tetratelabs/tis/agent:v0.0.1@sha256:39b9c6b6f326650421d714d9744e5685c67241432159376bedf2f2b386ec8383
  pullPolicy: Always
registrySync:
  publishNamespace: ''
  consul:
    endpoint: ''
    namespace: ''
    token: ''
  cloudmap:
    regiion: us-east-1
serviceAccount:
  create: true
  annotations: {}
  name: ''
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: {}
affinity: {}

---