istios:
  - version: "1.13.3"
  - version: "1.13.5"
  - version: "1.14.1"
  - version: "1.14.3"
  - version: "1.14.4"
  - version: "1.14.5"
  - version: "1.14.6"
  - version: "1.15.1"
  - version: "1.15.3"
  - version: "1.15.4"
  - version: "1.16.0"
  - version: "1.16.1"
  - version: "1.16.2"
  - version: "1.16.3"
  - version: "1.16.4"
    tetrate: "4"
  - version: "1.16.5"
  - version: "1.16.6"
  - version: "1.16.7"
  - version: "1.17.1"
  - version: "1.17.2"
  - version: "1.17.3"
  - version: "1.17.4"
  - version: "1.17.5"
  - version: "1.17.6"
  - version: "1.18.0"
  - version: "1.18.1"
  - version: "1.18.2"
    tetrate: "1"
  - version: "1.18.3"
  - version: "1.19.0"

addons:
  - istio-registry-sync

demos:
  - istio-monitoring-demo

dependencies:
  - name: grafana
    url: "https://grafana.github.io/helm-charts"
  - name: prometheus
    url: "https://prometheus-community.github.io/helm-charts"
