apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: '{{ .Release.Namespace }}'
  name: {{ include "agent.serviceAccountName" . }}-secret-reader-role
rules:
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - 'create'
      - 'update'
      - 'get'
      - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: istio-system
  name: {{ include "agent.serviceAccountName" . }}-istio-system-reader-role
rules:
  - apiGroups:
      - ''
    resources:
      - 'pods'
    verbs:
      - 'get'
      - 'list'
  - apiGroups:
      - ''
    resources:
      - 'pods/proxy'
    verbs:
      - 'get'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent.serviceAccountName" . }}-secret-reader-role-binding
  namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: Role
  name: {{ include "agent.serviceAccountName" . }}-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent.serviceAccountName" . }}-istio-system-reader-role-binding
  namespace: istio-system
roleRef:
  kind: Role
  name: {{ include "agent.serviceAccountName" . }}-istio-system-reader-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent.serviceAccountName" . }}-cluster-role
rules:
  - apiGroups: ['networking.istio.io']
    resources: ['serviceentries']
    verbs: ['create', 'get', 'list', 'watch', 'patch', 'delete', 'update']
  - apiGroups: ['']
    resources: ['services']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agent.serviceAccountName" . }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.serviceAccountName" . }}
    namespace: '{{ .Release.Namespace }}'
